Repository libretiny-eu/libretiny, pull requests merged in 2024-01, with the labels that each got.

#209 [beken-72xx] Allow connecting to specific BSSID if provided
  cores/beken-72xx/arduino/libraries/WiFi/WiFi.cpp
  cores/beken-72xx/arduino/libraries/WiFi/WiFiPrivate.h
  cores/beken-72xx/arduino/libraries/WiFi/WiFiSTA.cpp
Labels: enhancement, BK7231

#220 [beken-72xx] Improve ddev ADC support
  cores/beken-72xx/arduino/src/wiring_analog.c
Labels: bug, BK7231

#223 [docs] Use official ESPHome version, add LT dev version guide
  docs/projects/esphome.md
Labels: documentation, esphome

#226 [beken-72xx] Free list returned by wlan_sta_scan_result()
  cores/beken-72xx/arduino/libraries/WiFi/WiFiScan.cpp
  cores/common/arduino/libraries/api/WiFi/WiFiScan.cpp
  cores/realtek-amb/arduino/libraries/WiFi/WiFiScan.cpp
Labels: BK7231, quality

#240 [libs] Fix MD5 calculation during OTA update
  cores/common/arduino/libraries/common/Update/Update.cpp
Labels: bug, RTL8710B
